config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params # from the form
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movie = Movie.all
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add New Bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit class: 'btn btn-primary my-3' %>
  <% end %>
  <p>
    <%= link_to '< Lists', lists_path, class: 'btn-light opacity-25 text-decoration-none' %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/lists/index.html.erb
<div class="container">
  <h1>Lists</h1>
  <%= link_to "Add", new_list_path, class: 'btn btn-primary my-3' %>

  <% @lists.each do |list| %>
  <div>
    <%= link_to list_path(list['id']), class: 'text-decoration-none' do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path list.photo.url %>')">
        <%= list.name %>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Add to List</h1>
  <p>
    <%= link_to '< Lists', lists_path, class: 'btn-light opacity-25 text-decoration-none' %>
  </p>
  <% if @list.errors.any? %>
    <% @list.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
  <%= render 'lists/form' %>
</div>

app/views/lists/show.html.erb
<div class="container mt-2">
  <h1>Lists</h1>
  <p>
    <%= link_to '< Lists', lists_path, class: 'btn-light opacity-25 text-decoration-none' %>
  </p>
  <%= cl_image_tag(@list.photo.key, width: 700, height: 300, crop: :fill) %>
  <div class="row justify-content-around">
  <div class="col-12 col-lg-6">
    <h1 class="my-3"><%= @list.name  %></h1>
    <div class="d-flex align-items-center">
      <% @list.bookmarks.each do |bookmark| %>
      <div class="cards">
        <div class="card-product">
          <img src="<%= bookmark.movie.poster_url %>">
          <div class="card-product-infos">
            <h2><%= bookmark.movie.title %></strong></h2>
            <p><%= bookmark.movie.overview %></p>
            <p><%= bookmark.movie.rating %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  </div>
    <%= link_to "Add Bookmark", new_list_bookmark_path(@list), class: 'btn btn-primary my-3' %>
</div>